---
version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.0
jobs:

  terraform:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./infrastructure
      - terraform/validate:
          path: ./infrastructure
      - terraform/plan:
          path: ./infrastructure
      - terraform/apply:
          path: ./infrastructure
      - run: cd ./infrastructure  
      - run: terraform output first_web_server_ssh_key
      # - run: terraform output db_subnet_cidr_block -state=./infrastructure/terraform.tfstate
      # - run: terraform output db_ip -state=./infrastructure/terraform.tfstate
      # - run: terraform output first_db_server_id -state=./infrastructure/terraform.tfstate
      # - run: terraform output first_db_server_public_ip -state=./infrastructure/terraform.tfstate
      # - run: terraform output first_db_server_ssh_key -state=./infrastructure/terraform.tfstate
      # - run: terraform output first_web_server_ssh_key -state=./infrastructure/terraform.tfstate
      # - run: terraform output http_ip -state=./infrastructure/terraform.tfstate
      # - run: terraform output http_subnet_cidr_block -state=./infrastructure/terraform.tfstate
      # - run: terraform output second_db_server_id -state=./infrastructure/terraform.tfstate
      # - run: terraform output second_db_server_public_ip -state=./infrastructure/terraform.tfstate
      # - run: terraform output second_db_server_ssh_key -state=./infrastructure/terraform.tfstate
      # - run: terraform output second_web_server_ssh_key -state=./infrastructure/terraform.tfstate
      # - run: terraform output third_db_server_id -state=./infrastructure/terraform.tfstate
      # - run: terraform output third_db_server_public_ip -state=./infrastructure/terraform.tfstate
      # - run: terraform output third_db_server_ssh_key -state=./infrastructure/terraform.tfstate
      # - run: terraform output vpc_cidr_block -state=./infrastructure/terraform.tfstate
      - terraform/destroy:
          path: ./infrastructure


  # terratest:
  #   docker:
  #     x
  #   steps:
  #     - checkout

  #     - run: wget https://releases.hashicorp.com/terraform/1.3.5/terraform_1.3.5_linux_amd64.zip

  #     - run: sudo unzip terraform_1.3.5_linux_amd64.zip -d /usr/local/bin

  #     - run: ls -l /usr/local/bin

  #     - run: terraform -version

  #     - run: ls -la 

  #     - run: go mod init mytests
  #     - run: go mod tidy

  #     - run:
  #         name: Run tests
  #         command: go test -v 
  




workflows:
  deploy_infrastructure:
    jobs:

    - terraform

















