---
version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.0
jobs:

  terraform:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./infrastructure
      - terraform/validate:
          path: ./infrastructure
      - terraform/plan:
          path: ./infrastructure
      - terraform/apply:
          path: ./infrastructure
      - terraform/destroy:
          path: ./infrastructure


  # terratest:
  #   docker:
  #     - image: cimg/go:1.19.4
  #   steps:
  #     - checkout

  #     - run: wget https://releases.hashicorp.com/terraform/1.3.5/terraform_1.3.5_linux_amd64.zip

  #     - run: sudo unzip terraform_1.3.5_linux_amd64.zip -d /usr/local/bin

  #     - run: ls -l /usr/local/bin

  #     - run: terraform -version

  #     - run: ls -la 

  #     - run: go mod init mytests
  #     - run: go mod tidy

  #     - run:
  #         name: Run tests
  #         command: go test -v 
  




workflows:
  deploy_infrastructure:
    jobs:
    
    - terraform

















